dist: trusty
language: R
services:
- docker
cache:
- packages
env:
  global:
  - DOCKERHUB_ORGANISATION=komparo
  - DOCKERHUB_REPO=tde_method_random
  - secure: o0NOZXKOHTUz72zsrChXl18pSEoBdEUzQJ+QVLnLJ47Ln6eL1VkKEVaUG0Ng0CYztg7wEwfQ42PdryKP0hW39JcLzq2XlgxXMYD5yDDjJpYo6+kZt+aadZU/TMw4bPJfNZu6zLEp8iAt2XmVCXxYkNhsKI7Diby+//lMyqAmUrOzwAEe6QEPKQBAUKBw+FLRrvrcaEmcHnsZvMgHq/6R038anJxk78/e4cKyc+SVueyg0MFe9luvJkGuRLQ8D6TgDwBpLqbIxTIK0hc8YKVcNRaVPiwhfLgrn34TMOB4MlbTUBXsgUKNxDPwjKhmWqLTU0sCyIXxLczOcU64IOARuYH6ORUexzzwIALFlPmp/Ar2oZhpxq47am8XWopkZ2/V2sVl3Q4eKuFSvjj+7bq1BGmDP/NpskBwH1k3ymqzDGXcPrPvVylHzrMmRT8c8OuEVmCtVScyf3jNPmj4ev6PYy4X1a0w2T7oGYUdzlIrI2L10Xs8xs7Hqb6UyM4NwK3/EBtI98Pi6fsWoM1CalwHzMboQ0EEyTll1CJVfgNODeiUhi62lDNIKJd61lviw4fbz/0MuCDA0XDn9DXjo/yNAe+67fYsrt/ToC+UmpNgza5nZyb6n7azEbnOTc5kDyDMH1cUN63CSATou1gM/LjSRb9MZYpP0pgXFxWBo3aaofI=
before_install:
- git clone https://github.com/komparo/travis_scripts.git
- |
  if [[ -z "${DOCKERHUB_PASSWORD}" ]]; then
    echo "Not logging in to dockerhub"
  else
    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  fi
- docker pull ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} || true
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('komparo/tde/package@devel')"
after_install:
- docker images
script:
- Rscript test.R
deploy:
  provider: script
  script: echo "deploy!"
  on:
    branch: master
  skip_cleanup: true
