dist: trusty
language: R
services:
- docker
cache:
- packages
env:
  global:
  - DOCKERHUB_ORGANISATION=komparo
  - DOCKERHUB_REPO=tde_method_random
  - secure: LlSZCOyfFGIrBlBoSndtKDkCI0ZCHkyXKZch3NzEVnCx/n4tPB6RCkZUn6isS3fELRZPubEN1b6JYaOkqL6CjwE7/de52XCzzVoU7B46LdT3zYJJih2OVLmZmI+HPg8ZRut4fnalnWasq+CRRNYPjC8BHq7UDZe+CjqRFRnjhPUmTtHd5eubcIibiVgKDlyPWxQDR5F6rXlIlEh1ZJwU/s2iAXdHnFrH56/hiX87R9smSJMm8XpT2Vx1thSaN18OspT15e1dozXL1tEWANyTtQ5o7cvITM0tHeUdvqONQBesvTKfZJFLokxGNFsEAfY0ctKIfUs3QR7q37sMuMwYQAZ4qoZ5EBM6/zY2dnn5K8iiyAVDh7lPiFbha6Ay0CIWJS8Slf0jnEL0EhNXPYIDbpPZeQh6K5l+PUunKdCXs9d/rmfvaY75nkBfdWoy1YCxGVLaq008/Yft7RKdpPQVIb3+KHsojBqB7a8U2qYukzpXrvXvWnb9K+nOb/bKxC3koRwFdYI4B4/y0vpBCywdKIwasxX2AW3xkQD5ZbPuae7l0SeCumqYGTe6LN0IbjPoDRVauXtV5fXQjdFWyQCGeOYPWhRTDAUb0iwS1TT7yWLk7nermV0Y4Ga7M+IjGuLp0bvLV3XeEsJx2x4ZoLX9K+4L2VnMEPoFDwFm9tTTeME=
before_install:
- git clone https://github.com/komparo/travis_scripts.git
- |
  if [[ -z "${DOCKERHUB_PASSWORD}" ]]; then
    echo "Not logging in to dockerhub"
  else
    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  fi
- docker pull ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} || true
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('komparo/certigo@devel')"
after_install:
- docker images
script:
- Rscript test.R
deploy:
  provider: script
  script: echo "deploy!"
  on:
    branch: master
  skip_cleanup: true
