---
title: "Overall results"
output: html_document
---

# Datasets

```{r setup, echo=FALSE, include=FALSE}
library(tidyverse)
knitr::opts_knit$set(root.dir = knit_root_dir)
```

```{r}
datasets <- inputs[["datasets"]] %>% 
  as_tibble() %>% 
  mutate(
    gene_expression = map(gene_expression, read.table, row.names = 1, header = TRUE, sep = ","),
    n_cells = map_int(gene_expression, nrow),
    n_features = map_int(gene_expression, ncol)
  )
```

```{r}
datasets %>% 
  select(n_cells, n_features) %>% 
  gather("feature", "n") %>% 
  ggplot(aes(feature, n)) +
   geom_boxplot() +
  theme_bw()
```

# Evaluation

```{r, fig.width=10, fig.height=10}
scores <- inputs$scores %>% 
    as_tibble() %>% 
    mutate(
        scores = map(scores, jsonlite::read_json, simplifyVector = TRUE) %>% map(as_tibble)
    ) %>% unnest(scores)

scores %>% 
  gather("metric", "value", -method_id, -dataset_id) %>% 
  ggplot(aes(method_id, value)) +
    geom_boxplot() +
    theme_bw() +
    facet_wrap(~metric, scales = "free_x") +
    coord_flip()
```

# Conclusion

Meow.